# This code is licensed under the MIT License, view the file "LICENSE" or go to...
# https://github.com/EliStillCantCode/VariableTypeFunctions/blob/master/LICENSE
# ...to see restrictions and permissions